# Generated by Django 3.1 on 2022-11-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221004_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payement_method',
            new_name='payment_method',
        ),
    ]
